### ISSUE TITLE
medevac.injectWoundedGroup("extract1", false) causes error with _spawnedGroup:isActive() 

### ISSUE THREAD

**Issue by shagratdcs** [ciribob/DCS-Medevac#5]
Error Message from DCS[string ".path.":1402: attempt to call method 'isActive' (a nil value)
stack traceback: [C]: in function 'isActive'
[string ".path.":1402:in function 'injectWoundedGroup' [string "medevac.injectWoundedGroup("extract1", false)"]:1 in main chunk

I simpy tried to check the inject function works while trying to add evacuation for infantry to CTTS... seems, the function is not working at all.

Put a simple 'Do script' in the mission editor with 'medevac.injectWoundedGroup("extract1", false)'

**Comment by ciribob** [comment]
Fixed! Sorry my screw up.

**Comment by shagratdcs** [comment]
No problem, just ran across that one...still fighting with CTTS to identify and inject the group. :grin:
